# Generated by Django 5.0.6 on 2024-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_extension',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
