# Generated by Django 5.0.6 on 2024-07-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_birthplace_item_citizenship_item_civil_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
